name: Bug Report for Examples

description: Create a report to help us improve
labels: 
  - bug

body:
  - type: textarea
    id: code
    attributes:
      label: the code that reproduces this issue or a replay of the bug
      description: |
        public repo link or copy code
    validations:
      required: true
  - type: textarea
    id: Describe
    attributes:
      label: Describe the bug
      value: |
        **Describe the bug**
        A clear and concise description of what the bug is.

        **Expected behavior**
        A clear and concise description of what you expected to happen.

        **Screenshots**
        If applicable, add screenshots to help explain your problem.
 
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: error log
      description: Add any other context about the problem here.
    validations:
      required: true
